### ISSUE TITLE
linuxmuster-client-addso-setup does not import certificate

### ISSUE THREAD

**Issue by lemertens** [linuxmuster/linuxmuster-client-adsso#1] opened 2018-11-17 15:59 UTC
I installed a new test system with the lml7-server and firewall appliance, using default values. Did a fresh install of Ubuntu 18.04 Mate for a client. Added linuxmuster-client-addso and ran linuxmuster-client-addso-setup. Setup does fine to the point where the certificate cacert.perm is meant to be copied from the server.
Error message is 
```
"mount error: Required key is not available" 
"cannst stat /var/lib/samba/sysvol/linuxmuster..... No such file or directory"
umount: /var/lib/samba/sysvol
```
So it seems the mount of /var/lib/samba/sysvol is not succesfull

**Comment by ironiemix** [comment] 2019-05-20 19:24
I cannot reproduce this error?

**Comment by jolly-jump** [comment] 2019-11-17 20:23
Hi, I could reproduce the problem: 
You are not allowed to run linuxmuster-client-adsso-setup from within an logged in teacher user.
You should do it from the linuxadmin user or from remote using ssh and the root user.
Ok?
Think we can close this.

**Closed as completed by jolly-jump** 2019-11-17 20:23 UTC
